version: '3.8'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=paths
      - MYSQL_ROOT_PASSWORD=gems2022
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: paths_api
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: gems2022
      DB_NAME: paths
    links: 
      - db
    volumes:
      - ./:/src

volumes:
  db:
    driver: local